# Generated by Django 3.2.7 on 2021-09-19 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='cat',
            new_name='game',
        ),
        migrations.AddField(
            model_name='game',
            name='photos',
            field=models.CharField(default='No box art', max_length=500),
            preserve_default=False,
        ),
    ]
